config/routes.rb
Rails.application.routes.draw do

  resources :properties
  get "/dashboard", to: "dashboard#index"
  # get 'dashboard/properties'
  # get 'dashboard/reports'

  root 'static_pages#home'

  get '/blog', to: 'static_pages#blog'
  get '/advertising', to: "static_pages#advertising"
  get 'signup', to: 'accounts#new'

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :accounts
  resources :properties, only: [:create,:update, :destroy]
end

app/models/account.rb
class Account < ApplicationRecord

    has_many :properties, dependent: :destroy

    before_save :downcase_email

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :last_name, presence: true, length: { maximum: 50 }
    validates :first_name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}, length: { maximum: 250 }
    validates :password, presence: true, length: { minimum: 6 }

    has_secure_password

    def self.digest string

        cost = if ActiveModel::SecurePassword.min_cost
            BCrypt::Engine::MIN_COST
                else
                    BCrypt::Engine.cost
                end

        BCrypt::Password.create string, cost: cost
    end

    def full_name
      "#{first_name} #{last_name}"
    end

    private

    def downcase_email
        email.downcase!
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :account
  scope :newest, -> { order(created_at: :desc) }
  has_one_attached :photo
  validates :name, presence: true, length: { maximum: 140 }
  validates :address, presence: true, length: { maximum: 140 }
  validates :price, presence: true, length: { maximum: 140 }
  validates :rooms, presence: true, length: { maximum: 140 }
  validates :bathrooms, presence: true, length: { maximum: 140 }
  validates :photo, content_type: { in: %w[image/jpeg image/gif image/png],
                                    message: "must be a valid image format" },
                    size:         { less_than: 5.megabytes,
                                    message: "should be less than 5MB" }

  def display_photo
    photo.variant resize_to_limit: [12500, 12500]
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :load_account, only: [:show, :edit]
  before_action :set_sidebar, only: [:show]

  def show
    @agent = @account
    @agent_properties = Property.where(account_id: @agent.id)
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new account_params
    if @account.save
      flash[:success] =  ".create_user_success"
      redirect_to @account
    else
      render :blog
    end
  end

  private

  def set_sidebar
    @show_sidebar = true
  end

  def load_account
    @account = Account.find_by id: params[:id]
    return if @account

    flash[:warning] = ".user_not_found"
    redirect_to root_path
  end

  def account_params
    params.require(:account)
          .permit(:last_name,:first_name, :email, :telephone, :company, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def logged_in_user
    return if logged_in?

    flash[:danger] = t "require_login"
    redirect_to login_url
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_sidebar

  def index
  end

  def properties
  end

  def reports
  end

  private

  def set_sidebar
    @show_sidebar = true
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :set_sidebar, except: [:show]


  def index
    @properties = Property.all
  end

  def show
    @agent = @property.account
    @agent_properties = Property.where(account_id: @agent.id).where.not(id: @property.id)
  end

  def new
    @property = Property.new
  end

  def edit
  end

  def create
    @property = current_account.properties.build(property_params)
    @property.photo.attach(params[:property][:photo])
    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_property
    @property = Property.find(params[:id])
  end

  def set_sidebar
    @show_sidebar = true
  end

  def property_params
    params.require(:property).permit(:name, :address, :price, :rooms, :bathrooms, :details,
                                     :for_sale, :available_date, :parking_spaces, :photo)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    account = Account.find_by email: params[:session][:email].downcase
    if account&.authenticate(params[:session][:password])
      authenticate account
    else
      flash.now[:danger] = "invalid_email_password_combination"
      render :blog
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end

  def authenticate account
    log_in account
    redirect_to account
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @properties = Property.newest
  end

  def blog
  end

  def advertising
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
    def gravatar_for account
        gravatar_id = Digest::MD5.hexdigest(account.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: account.last_name, class: "gravatar")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title page_title
        base_title = t ".title_global"
        page_title.blank? ? base_title : "#{page_title} | #{base_title}"
    
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def property_thumbnail(property)
    img = property.photo.present? ? property.photo : ''
    image_tag img, class: 'img-thub'
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in account
    session[:account_id] = account.id
  end



  def current_account
    @current_account ||= Account.find_by(id: session[:account_id]) if session[:account_id]
  end


  def logged_in?
    current_account.present?
  end

  def log_out
    session.delete :account_id
    @current_account = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/accounts/new.html.erb
<main class="form-signin">

  <%= form_for @account do |f| %>
    <section class="text-center">
        <img class="mb-4" src="https://img.icons8.com/clouds/2x/fa314a/apple-camera.png" alt="" width="102" height="87">
        <h1 class="h3 mb-3 fw-normal">Please Sign Up</h1>
    </section>

    <%= render "shared/error_messages" %>

    <%= f.label :last_name, t(".name") %>
    <%= f.text_field :last_name, class: "form-control" %>
    <%= f.label :first_name, t(".name") %>
    <%= f.text_field :first_name, class: "form-control" %>
    <%= f.label :email, t(".email") %>
    <%= f.email_field :email, class: "form-control" %>

    <%= f.label :telephone, t(".Phone") %>
    <%= f.telephone_field :telephone , class: "form-control"%>


    <%= f.label :company, t(".company") %>
    <%= f.text_field :company , class: "form-control"%>

    <%= f.label :password, t(".password") %>
    <%= f.password_field :password, class: "form-control" %>
    <%= f.label :password_confirmation, t(".password_confirm") %>
    <%= f.password_field :password_confirmation, class: "form-control" , type: "password_confirmation"%>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>

    <%= f.submit "Create my account", class: "w-100 btn btn-lg btn-primary" %>

    <section class="text-center">
      <p class="mt-5 mb-3 text-muted">&copy; 2021</p>
    </section>
  <% end %>

</main>

app/views/accounts/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @account %>
        <%= @account.last_name %> <%= @account.first_name %>, <%= @account.email %>,
        <%= @account.url %>,<%= @account.created_at %>, <%= @account.updated_at %>
      </h1>
    </section>
    <section class="mt-5 mb-5">
      <div class="container" bis_skin_checked="1">
        <div class="row" bis_skin_checked="1">
          <div class="col-12">
            <p class="h3 mb-3">Other properties by this agent</p>
          </div>
          <%= render "properties/lastest_properties", properties: @agent_properties %>
        </div>
      </div>
  </section>
  </aside>
</div>

app/views/dashboard/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h1">Dashboard</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group me-2">
      <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
      <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
    </div>
    <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar" aria-hidden="true"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
      This week
    </button>
  </div>
</div>

<h2>Section title</h2>
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Header</th>
        <th scope="col">Header</th>
        <th scope="col">Header</th>
        <th scope="col">Header</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1,001</td>
        <td>random</td>
        <td>data</td>
        <td>placeholder</td>
        <td>text</td>
      </tr>
      <tr>
        <td>1,002</td>
        <td>placeholder</td>
        <td>irrelevant</td>
        <td>visual</td>
        <td>layout</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/dashboard/properties.html.erb
<h1>Dashboard#properties</h1>
<p>Find me in app/views/dashboard/properties.html.erb</p>

app/views/dashboard/reports.html.erb
<h1>Dashboard#reports</h1>
<p>Find me in app/views/dashboard/reports.html.erb</p>

app/views/layouts/_validation.html.erb
<% if item.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(item.errors.count, "error") %> prohibited this property from being saved:</h2>

  <ul>
    <% item.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body >
    <% if @show_sidebar.nil? %>
      <header>
        <%= render "layouts/nav/header" %>
      </header>
      <%= yield %>
    <% else %>
      <%= render "layouts/nav/dashboard" %>
      <div class="container">
        <div class="container-fluid" bis_skin_checked="1">
          <div class="row" bis_skin_checked="1">
            <%= render "layouts/nav/sidebar" %>
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 mt-3">
              <%= yield %>
            </main>
          </div>
        </div>
      </div>
    <% end %>
    <br>

    <div id="notifications"><%= notice %></div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script>
      feather.replace()
    </script>
  </body>
</html>

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="<%= logged_in? ? dashboard_path : root_path %>">BDS System</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to "Log out" , logout_path, method: :delete ,class: "nav-link"  %>
    </li>
  </ul>
</nav>

app/views/layouts/nav/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <%= link_to "BDS", root_path, class: "nav-link"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
      <li class="nav-item">
          <% if logged_in? %>
          <%= link_to "Dashboard", dashboard_path, class: "nav-link"%>
          <% else %>
          <%= link_to "Home", root_path, class: "nav-link"%>
          <% end %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Lastest</a>
        </li>
        <li class="nav-item">
          <%= link_to "Blog", blog_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Advertising", advertising_path, class: "nav-link"%>
        </li>

        <% if logged_in? %>

        <li class="nav-item">
          <%= link_to "Logout", logout_path, method: :delete ,class: "nav-link"%>
        </li>

        <% else %>
        <li class="nav-item">
          <%= link_to "Sign In", login_path , class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", signup_path, class: "nav-link"%>
        </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="position-sticky pt-3">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to dashboard_path, class: "nav-link" do %>
          <i data-feather="home"></i>
          Dashboard
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to properties_path, class: "nav-link" do %>
          <i data-feather="file-text"></i>
          Property
        <% end %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i data-feather="gift"></i>
          Products
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i data-feather="users"></i>
          Customers
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i data-feather="bar-chart-2"></i>
          Reports
        </a>
      </li>
      <li class="nav-item">
        <%= link_to current_account, class: "nav-link" do %>
          <i data-feather="settings"></i>
          Account Settings
        <% end %>
      </li>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Saved reports</span>
      <a class="link-secondary" href="#" aria-label="Add a new report">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
          Current month
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
          Last quarter
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
          Social engagement
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
          Year-end sale
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/properties/_agent_details.html.erb
<div class="text-center border p-4 pb-4 ml-lg-4">
  <div class="mb-2">
    <%= gravatar_for @agent %>
  </div>
  <h3 class="h4 m-0"><%= @agent.full_name %></h3>
  <p><%= @agent.company %></p>
  <div class="row">
    <div class="col-12">
      <button class="btn btn-block btn-info text-uppercase mb-3 mt-3"><i class="fas fa-phone mr-2 "></i><span><%= @agent.telephone %></span></button>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 pr-1">
      <%= link_to "Profile", current_account, class: "btn btn-secondary text-uppercase btn-block" %>
    </div>
    <div class="col-md-6 pl-1">
      <button class="btn btn-block btn-success text-uppercase" data-toggle="modal" data-target="#contact-modal"><i class="fas fa-envelope mr-2"></i>Email</button>
    </div>
  </div>
</div>

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>

  <%= render "layouts/validation", item: @property%>

  <div class="field">
    <%= form.label :name , class: "h5"%>
    <%= form.text_field :name , class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :address , class: "h5"%>
    <%= form.text_field :address , class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :price ,"Total Price (for sale) / Monthly Price (rental)", class: "h5"%>
    <%= form.number_field :price , class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :rooms , class: "h5"%>
    <%= form.number_field :rooms , class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :bathrooms , class: "h5"%>
    <%= form.number_field :bathrooms , class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :details , class: "h5"%>
    <%= form.text_area :details , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :for_sale %>
    <%= form.select :for_sale, options_for_select({ "Yes" => true, "No" => false }, @property.for_sale), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :available_date %>
    <%= form.date_field :available_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :parking_spaces %>
    <%= form.number_field :parking_spaces, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :photo %>
    <%= form.file_field :photo, class: "form-control" , accept: "image/jpeg,image/gif,image/png"%>
  </div>

  <div class="actions">
    <%= form.submit "Save Property", class: "btn btn-success"%>
  </div>
<% end %>


<script type="text/javascript">
  $("#property_photo").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
    }
  });
</script>

app/views/properties/_lastest_properties.html.erb
<% properties.each do |property| %>
<div class="col-4">
  <div class="property border">

    <%= link_to(property_thumbnail(property), property_path(property)) %>
      <!-- FIX THIS PROPERTY THUMBNAIL URL -->


    <div class="property-summary p-3">
      <h3 class="h5"><%= link_to property.name,property_path(property), class: "text-dark" %></h3>

      <span class="mr-2">
        <%= property.rooms %>
        <i class="fas fa-bed text-muted ml-1"></i>
      </span>
      <span class="mr-2">
        <%= property.bathrooms %>
        <i class="fas fa-bath text-muted ml-1"></i>
      </span>
      <span>
        <%= property.parking_spaces %>
        <i class="fas fa-car text-muted ml-1"></i>
      </span>

      <p class="mt-2"><%= property.address %></p>
    </div>
  </div>
</div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.price %></td>
        <td><%= property.rooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= property.photo %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path, class: 'btn btn-success'%>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/shared/_error_messages.html.erb
<% if @account.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@account.errors.count, "error") %>.
    </div>
    <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/advertising.html.erb
<% provide(:title, "Advertising") %>

<h1>StaticPages#advertising</h1>
<p>Find me in app/views/static_pages/advertising.html.erb</p>

app/views/static_pages/blog.html.erb
<% provide(:title, "Blog") %>

<h1>StaticPages#blog</h1>
<p>Find me in app/views/static_pages/blog.html.erb</p>